os: unstable

platform:
 - x86

install:
  - ps: (new-object System.Net.WebClient).Downloadfile("https://downloads.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-posix/dwarf/i686-4.9.2-release-posix-dwarf-rt_v3-rev0.7z", "c:\mingw.7z")
  - 7z x -y "c:\mingw.7z" -o"C:\" > nul
  - set PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;C:\mingw32\bin;%QTDIR%\bin;%PATH%
  - ps: (new-object System.Net.WebClient).Downloadfile("http://itdaniher.com/static/libusb-1.0-hp.7z", "c:\libusb.7z")
  - 7z x -y "c:\libusb.7z" -o"C:\libusb" > nul

build_script:
  - mingw32-make
  - appveyor PushArtifact libsmu.dll
  - appveyor PushArtifact libsmu.hpp
  - echo EXPORTS > libsmu.def
  - SET PATH=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\%platform%;%PATH%
  - for /f "usebackq tokens=4,* delims=_ " %i in (`dumpbin /exports "libsmu.dll"`) do if %i==libsmu echo %i_%j >> libsmu.def
  - dlltool --dllname libsmu.dll --input-def libsmu.def --output-lib libsmu.lib
  - appveyor PushArtifact smu.exe
  - appveyor PushArtifact libsmu.lib
  - appveyor PushArtifact libsmu.def
